import type { Metadata } from "next"
/** Stylesheet */
import "@/assets/styles/globals.css"
import "@/assets/styles/fonts.css"

export const metadata: Metadata = {
  title: "Noey Ignacio (@noeyislearning)",
  description: "Generated by create next app",
}

/** Components */
import SideNav from "@/components/layouts/nav/SideNav"
import { Providers } from "@/redux/Providers"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="font-sn-pro" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <main className="z-10 h-screen tracking-tight text-black antialiased">
          <div className="h-screen w-screen">
            <Providers>
              <SideNav />
              {children}
            </Providers>
          </div>
        </main>
      </body>
    </html>
  )
}

export const viewport = {
  width: "device-width",
  height: "device-height",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: "no",
  viewportFit: "cover",
  suppressHydrationWarning: true,
  themeColor: "white",
  colorScheme: "only light",
}
